# when ever we use docker we need super user permissions
sudo: required 
services:
  - echo "In the  services"
  - docker        #We are telling Travis that we need docker CLI pre-installed.

# This section will have a series of different commands before our tests has ran
before_install:     
  - echo "BEFORE INSTALL START"
  - docker build -t skandukuri03/docker-react -f Dockerfile.dev .  #We have to build docker image before the build

#the below section tell travis how to run the test - a series of commands to test-- --coverage will exit the test after done...
script:
 #  - docker run skandukuri03/docker-react npm run test -- --coverage   ----> This did not work for me...
 # - docker run -e CI=true skandukuri03/docker-react npm run test
  - docker run -e CI=true skandukuri03/docker-react npm run test -- --coverage