sudo: required 
services:
  - docker

before_install:     
  - echo "BEFORE INSTALL START"
  - docker build -t skandukuri03/docker-react -f Dockerfile.dev .  
  
script:
  - docker run skandukuri03/docker-react npm run test -- --coverage