FROM node:alpine
WORKDIR '/app'
COPY package.json .
RUN npm install
#if we are using the docker-compose.yaml .... We are mounting the volume and we do not need to copy the files to conatiner
COPY . .    
CMD ["npm","run","start"]